import { describe, expect, it } from 'vitest';
import { sanitizeSafeAudioUrl } from '../lib/audio-security';

describe('sanitizeSafeAudioUrl security test suite', () => {
  it('allows safe blob URLs generated by browser recording', () => {
    const blobUrl =
      'blob:http://localhost:3000/b1c4e97a-9721-4f18-8be4-8f0a7cb54c5e';
    expect(sanitizeSafeAudioUrl(blobUrl)).toBe(blobUrl);
  });

  it('allows safe audio data URIs', () => {
    const dataAudioWebm =
      'data:audio/webm;base64,GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQRChYECGFOAZwE';
    expect(sanitizeSafeAudioUrl(dataAudioWebm)).toBe(dataAudioWebm);

    const dataAudioMp3 =
      'data:audio/mp3;base64,//uQxAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAA';
    expect(sanitizeSafeAudioUrl(dataAudioMp3)).toBe(dataAudioMp3);
  });

  it('allows safe relative audio file paths', () => {
    expect(sanitizeSafeAudioUrl('/sounds/whisper.mp3')).toBe(
      '/sounds/whisper.mp3',
    );
    expect(sanitizeSafeAudioUrl('/audio/notes/letter-1.webm')).toBe(
      '/audio/notes/letter-1.webm',
    );
  });

  it('allows safe verified http and https audio URLs', () => {
    expect(sanitizeSafeAudioUrl('https://example.com/audio/whisper.mp3')).toBe(
      'https://example.com/audio/whisper.mp3',
    );
    expect(sanitizeSafeAudioUrl('http://audio.mysite.org/song.ogg')).toBe(
      'http://audio.mysite.org/song.ogg',
    );
  });

  it('rejects dangerous javascript: and vbscript: URIs (XSS mitigation)', () => {
    expect(sanitizeSafeAudioUrl('javascript:alert(1)')).toBeUndefined();
    expect(
      sanitizeSafeAudioUrl('JAVASCRIPT:alert(document.cookie)'),
    ).toBeUndefined();
    expect(sanitizeSafeAudioUrl('vbscript:msgbox(1)')).toBeUndefined();
  });

  it('rejects html/text/svg data URIs containing payload or scripts (CWE-184 allowlist)', () => {
    expect(
      sanitizeSafeAudioUrl('data:text/html,<script>alert(1)</script>'),
    ).toBeUndefined();
    expect(
      sanitizeSafeAudioUrl('data:application/javascript,alert(1)'),
    ).toBeUndefined();
    expect(
      sanitizeSafeAudioUrl('data:image/svg+xml;base64,PHN2Zz48L3N2Zz4='),
    ).toBeUndefined();
    expect(
      sanitizeSafeAudioUrl('data:audio/webm;<script>alert(1)</script>'),
    ).toBeUndefined();
    expect(
      sanitizeSafeAudioUrl('data:text/plain;base64,SGVsbG8='),
    ).toBeUndefined();
  });

  it('rejects non-allowlisted schemes such as file:, about:, and mailto:', () => {
    expect(sanitizeSafeAudioUrl('file:///etc/passwd')).toBeUndefined();
    expect(sanitizeSafeAudioUrl('about:blank')).toBeUndefined();
    expect(sanitizeSafeAudioUrl('mailto:test@example.com')).toBeUndefined();
  });

  it('rejects inputs containing HTML meta-characters or injection tags', () => {
    expect(
      sanitizeSafeAudioUrl('<audio src="x" onerror="alert(1)">'),
    ).toBeUndefined();
    expect(
      sanitizeSafeAudioUrl('https://evil.com/" onfocus="alert(1)'),
    ).toBeUndefined();
    expect(
      sanitizeSafeAudioUrl("https://evil.com/' onmouseover='alert(1)"),
    ).toBeUndefined();
  });

  it('rejects protocol-relative URLs that attempt open redirection', () => {
    expect(sanitizeSafeAudioUrl('//evil.com/fake-audio.mp3')).toBeUndefined();
    expect(sanitizeSafeAudioUrl('/\\evil.com/audio.mp3')).toBeUndefined();
  });

  it('handles empty, null, undefined, and non-string inputs safely', () => {
    expect(sanitizeSafeAudioUrl(undefined)).toBeUndefined();
    expect(sanitizeSafeAudioUrl(null)).toBeUndefined();
    expect(sanitizeSafeAudioUrl('')).toBeUndefined();
    expect(sanitizeSafeAudioUrl('   ')).toBeUndefined();
    // @ts-expect-error testing non-string runtime inputs
    expect(sanitizeSafeAudioUrl(12345)).toBeUndefined();
  });
});
