/**
 * Audio URL Sanitization Utilities
 * Mitigates:
 * - DOM-based XSS (CWE-79, CWE-116, CodeQL js/xss-through-dom)
 * - Client-side URL Redirection / Resource Injection (CWE-601, CodeQL js/client-side-unvalidated-url-redirection)
 */

/**
 * Sanitizes voice note and audio URLs before passing to <audio> src or media sinks.
 * Strictly permits trusted audio schemes:
 * - blob: URLs (used for client-side recorded voice notes generated by URL.createObjectURL)
 * - data:audio/* (safe base64/encoded audio streams, strictly disallowing scripts/html/svg)
 * - Safe relative paths (e.g., /audio/whisper.mp3)
 * - Valid http: / https: URLs with verified protocols
 *
 * Rejects dangerous pseudo-protocols (javascript:, vbscript:, data:text/, data:application/),
 * unencoded HTML meta-characters (<, >, ", '), and protocol-relative URLs (//...).
 * Encodes output via encodeURI to prevent DOM text reinterpretation as HTML.
 * Returns undefined for any invalid or unsafe input.
 */
export function sanitizeSafeAudioUrl(url?: string | null): string | undefined {
  if (!url || typeof url !== 'string') return undefined;
  const trimmed = url.trim();
  if (!trimmed) return undefined;
  const lower = trimmed.toLowerCase();

  // Reject dangerous schemes, meta-characters, or script injection
  if (
    lower.startsWith('javascript:') ||
    lower.startsWith('vbscript:') ||
    lower.startsWith('data:text/') ||
    lower.startsWith('data:application/') ||
    lower.includes('<') ||
    lower.includes('>') ||
    lower.includes('"') ||
    lower.includes("'")
  ) {
    return undefined;
  }

  // Allow blob: URLs (for client-side recorded voice notes created via URL.createObjectURL)
  if (lower.startsWith('blob:')) {
    try {
      const withoutBlob = trimmed.slice(5);
      const innerUrl = new URL(withoutBlob);
      if (innerUrl.protocol === 'http:' || innerUrl.protocol === 'https:') {
        return encodeURI(trimmed);
      }
    } catch {
      if (/^blob:https?:\/\/[a-zA-Z0-9._:-]+\/[a-zA-Z0-9-]+$/i.test(trimmed)) {
        return encodeURI(trimmed);
      }
    }
    return undefined;
  }

  // Allow safe audio media data URIs (e.g. data:audio/webm;base64,...)
  if (
    lower.startsWith('data:audio/') &&
    !lower.includes('javascript') &&
    !lower.includes('html') &&
    !lower.includes('svg')
  ) {
    return encodeURI(trimmed);
  }

  // Allow safe relative paths (e.g. /audio/whisper.mp3)
  if (
    trimmed.startsWith('/') &&
    !trimmed.startsWith('//') &&
    !trimmed.startsWith('/\\')
  ) {
    if (/^\/[a-zA-Z0-9_./-]+$/i.test(trimmed) && !trimmed.includes('..')) {
      return encodeURI(trimmed);
    }
    return undefined;
  }

  // Allow valid http / https URLs with verified protocols
  if (lower.startsWith('https://') || lower.startsWith('http://')) {
    try {
      const parsed = new URL(trimmed);
      if (parsed.protocol === 'https:' || parsed.protocol === 'http:') {
        return encodeURI(parsed.href);
      }
    } catch {
      return undefined;
    }
  }

  return undefined;
}
